import keyMirror from 'keymirror';

export default keyMirror({
  USER_REQUEST: null,
  USER_SELECTED_FLIGHT_INFO: null,
  USER_RETURN_SELECTED_FLIGHT_INFO: null,
  USER_TOTAL_PRICE: null,
  PASSENGERS_INFO: null,
  RETURN_FLIGHT_PASSENGERS_INFO: null,
  SELECTED_PASSENGER: null,
  RETURN_FLIGHT_SELECTED_PASSENGER: null,
  RETURN_SELECTED_FLIGHT_INFO_RESETTING: null,
  USER_INFO_RESETTING: null,
  SELECTED_FLIGHT_INFO_RESETTING: null,
  IS_LOGGED_IN_USER: null,
  IS_REGISTERED_USER: null,
  PAYMENT_STATUS: null,
  TWO_WAY_REQUEST: null,
});
